### ISSUE TITLE
validation hooks

### ISSUE THREAD

**Issue by danieleades** [frozenlib/parse-display#10]
Any thoughts about adding validation hooks?

**Comment by frozenlib** [comment]
If `FromStr` is appropriate as a trait for validation, it's good to add a validation hooks.

But I'm not familiar with crates that need validation, so I don't know if FromStr is appropriate as a trait for validation.

I think this issue is going to be relevant to #7  as well.

**Comment by danieleades** [comment]
I think perhaps some of the more common use cases would be around parsing integers. Say, for an integer which represents a month, you would want to restrict the value to a particular range.

**Comment by frozenlib** [comment]
>  an integer which represents a month

For such types, it's safer to initialize with new function instead of constructor.

It might be nice to be able to specify how to initialize the value, as follows

```rust
use parse_display::{Display, FromStr};

#[derive(Display, FromStr)]
#[from_str(new = Self::new(_0))]
struct MonthInt(u8);

impl MonthInt {
    fn new(month: u8) -> Option<Self> {
        if 1 <= month && month <= 12 {
            Some(Self(month))
        } else {
            None
        }
    }
}
```

**Comment by danieleades** [comment]
I totally agree that's the safest bet. Shall we leave this here?

**Comment by frozenlib** [comment]
I implemented it in [these commits](https://github.com/frozenlib/parse-display/compare/eab568d82431a3e872899e748072254f441c586f...1c5fd57d06b2cf28752a160e49358997ea56bffd).
