### ISSUE TITLE
Omit `#[display(...)]` in newtype variants

### ISSUE THREAD

**Issue by nyuichi** [frozenlib/parse-display#20]
It would be helpful if `#[display(...)]` can be omitted for variants with a single parameter:

```
#[derive(Display)]
enum Foo {
    #[display("{0}")] // <-- omit this just like newtype structs
    Just(u32),
    #[display("nothing")]
    Nothing,
}
```

**Comment by frozenlib** [comment]
It seems to me that the variant name disappearing is not suitable for the default value.

For example, I don't think the following code is the kind of behavior that users want.
```rust
#[derive(Display)]
enum Either {
    Left(u32),
    Right(u32),
}

assert_eq!(Either::Left(10).to_string(), "10");
assert_eq!(Either::Right(10).to_string(), "10");
```

Unlike newtype structs, `#[display("{0}")]` in the variant can lead to an inappropriate implementation of `FromStr`.

```rust
#[derive(Display, FromStr, Eq, PartialEq, Debug)]
enum Foo {
    #[display("{0}")]
    Just(String),
    #[display("nothing")]
    Nothing,
}
let value0 = Foo::Just("nothing".into());
let value1: Foo = value0.to_string().parse().unwrap();
assert_eq!(value0, value1); // ASSERT FAILED!!
```

**Comment by nyuichi** [comment]
> Unlike newtype structs, #[display("{0}")] in the variant can lead to an inappropriate implementation of FromStr.

Yes, what was in my mind was to use it in combination with serde's untagged attribute.
untagged is useful but may introduce ambiguity in deserialization (users must use it carefully at their own risk), and I think that is the case with `FromStr`.

```
#[derive(Serialize, Deserialize, Display)]
#[serde(untagged)]
enum Foo {
  Var1(Bar),
  Var2(Baz),
}

#[derive(Serialize, Deserialize, Display)]
#[display("bar: {bar}")]
struct Bar {
  bar: String,
}

#[derive(Serialize, Deserialize, Display)]
#[display("baz: {baz}")]
struct Baz {
  baz: String,
}
```

**Comment by frozenlib** [comment]
If you put `#[display("{0}")]` on enum instead of variant, the behavior will be similar to `#[serde(untagged)]`. Isn't that enough?

```rust
use parse_display::Display;

#[derive(Display)]
#[display("{0}")]
enum Foo {
    Var1(Bar),
    Var2(Baz),
    #[display("nothing")]
    Nothing,
}

#[derive(Display)]
#[display("bar: {bar}")]
struct Bar {
    bar: String,
}

#[derive(Display)]
#[display("baz: {baz}")]
struct Baz {
    baz: String,
}

println!("{}", Foo::Var1(Bar { bar: "abc".into() }));
println!("{}", Foo::Var2(Baz { baz: "def".into() }));
println!("{}", Foo::Nothing);
```

**Comment by nyuichi** [comment]
Oh, I didn't know that functionality! That suffices. I'm closing this issue, thanks.
