### ISSUE TITLE
Allow ignoring enum variants from "from_str"

### ISSUE THREAD

**Issue by norcalli** [frozenlib/parse-display#25]
Sometimes it is desirable to not necessarily have complete symmetry in whether something can be constructed from a string even though it can be printed.

`#[from_str(ignore)]` on a variant would be basically what I'd want.

To be clear, the difference from current functionality is that the variant doesn't need to have `default` or anything in order to work.

**Comment by frozenlib** [comment]
Good idea.

I just implemented it with ee521d821390f27bd92dbd89d1bc79a5b29c0aa8.
