### ISSUE TITLE
style="lowercase" removes snake casing

### ISSUE THREAD

**Issue by bayarmunkh** [frozenlib/parse-display#30]
Hello!

This is more of a question whether the following is expected behavior or not. 
When using `lowercase` style, it remove all the underscores from that variant. As a workaround, declaring overrides on those affected variants is needed. See the example below.

```rust
#[display(style = "lowercase")]
pub enum MyEnum {
    #[display("var_a")] // without this override, it converts to `vara` by removing the underscore by default
    Var_A,
    VarB,
}
```

**Comment by frozenlib** [comment]
Hi.

This is the intended behavior.

However, it might be misinterpreted as a conversion by `str::to_lowercase`, so if a better name than `lowercase` is found, we might consider changing the style name in the future.

Also, it might be a good idea to add `to_lowercase` style that performs the conversion by `str::to_lowercase`.
