### ISSUE TITLE
How to parse `{` and `}` characters?

### ISSUE THREAD

**Issue by fritzrehde** [frozenlib/parse-display#37]
Suppose I would like to use:
```rust
#[derive(FromStr)]
#[display("{{a},{b}}")]
struct Ratingss {
    a: usize,
    b: usize,
}
```
to parse from the string `"{42,100}"`. This leads to an invalid display format. Is this a bug, or not allowed/not implemented?

**Comment by frozenlib** [comment]
In `parse-display`, just like in `std::fmt::format`, `{` and `}` must be expressed as `{{` and `}}`.
So, it should be written as follows.

```rust
#[derive(FromStr, Debug)]
#[display("{{{a},{b}}}")]
struct Ratingss {
    a: usize,
    b: usize,
}
```

**Comment by fritzrehde** [comment]
Ah thanks, I didn't know that about the syntax to print `{` und `}` in `std::fmt::format`.
